#! /usr/bin/env bash

set -euo pipefail

query="${1}"
variables="${2:-'{}'}"

scripts/run-query "${query}" "${variables}"

while inotifywait "${query}"
do
  scripts/run-query "${query}" "${variables}"
done
