#! /usr/bin/env bash

set -euvxo pipefail

echo ${2}

query="${1}"
variables="${2}"

http --verbose POST https://api.github.com/graphql \
  Authorization:"$(cat data/github-authorization)" \
  "query=@${query}" \
  "variables=${variables}"
